---
- hosts: webservers
  become: yes

  tasks:
    - debug: msg='Install Fail2ban'
    - apt: name=fail2ban force=yes
    - synchronize: src=/usr/src/fusionpbx-install.sh/debian/resources/fail2ban/freeswitch-dos.conf dest=/etc/fail2ban/filter.d/freeswitch-dos.conf
      delegate_to: "{{ inventory_hostname }}"
      notify:
      - restart fail2ban
    - synchronize: src=/usr/src/fusionpbx-install.sh/debian/resources/fail2ban/freeswitch-ip.conf dest=/etc/fail2ban/filter.d/freeswitch-ip.conf
      delegate_to: "{{ inventory_hostname }}"
      notify:
      - restart fail2ban
    - synchronize: src=/usr/src/fusionpbx-install.sh/debian/resources/fail2ban/freeswitch.conf dest=/etc/fail2ban/filter.d/freeswitch.conf
      delegate_to: "{{ inventory_hostname }}"
      notify:
      - restart fail2ban
    - synchronize: src=/usr/src/fusionpbx-install.sh/debian/resources/fail2ban/fusionpbx.conf dest=/etc/fail2ban/filter.d/fusionpbx.conf
      delegate_to: "{{ inventory_hostname }}"
      notify:
      - restart fail2ban
    - synchronize: src=/usr/src/fusionpbx-install.sh/debian/resources/fail2ban/nginx-404.conf dest=/etc/fail2ban/filter.d/nginx-404.conf
      delegate_to: "{{ inventory_hostname }}"
      notify:
      - restart fail2ban
    - synchronize: src=/usr/src/fusionpbx-install.sh/debian/resources/fail2ban/nginx-dos.conf dest=/etc/fail2ban/filter.d/nginx-dos.conf
      delegate_to: "{{ inventory_hostname }}"
      notify:
      - restart fail2ban
    - synchronize: src=/usr/src/fusionpbx-install.sh/debian/resources/fail2ban/jail.local dest=/etc/fail2ban/jail.local
      delegate_to: "{{ inventory_hostname }}"
      notify:
      - restart fail2ban
    - service: name=fail2ban state=started enabled=yes

  handlers:
    - name: restart fail2ban
      service: name=fail2ban state=restarted
