---
- hosts: webservers
  become: yes

  tasks:
    - debug: msg='Configure IPTables'
    - iptables: chain=INPUT in_interface=lo jump=ACCEPT
    - iptables: chain=INPUT ctstate=ESTABLISHED,RELATED jump=ACCEPT
    - iptables: chain=INPUT protocol=TCP destination_port=22 jump=ACCEPT
    - iptables: chain=INPUT protocol=TCP destination_port=80 jump=ACCEPT
    - iptables: chain=INPUT protocol=TCP destination_port=443 jump=ACCEPT
    - iptables: chain=INPUT protocol=TCP destination_port=5060:5069 jump=ACCEPT
    - iptables: chain=INPUT protocol=UDP destination_port=5060:5069 jump=ACCEPT
    - iptables: chain=INPUT protocol=TCP destination_port=5080 jump=ACCEPT
    - iptables: chain=INPUT protocol=UDP destination_port=5080 jump=ACCEPT
    - iptables: chain=INPUT protocol=UDP destination_port=16384:32768 jump=ACCEPT
# The below are commented out and waiting for ansible 2.2
#    - iptables: chain=INPUT protocol=ICMP icmp_type=echo-request jump=ACCEPT
#    - iptables: chain=INPUT protocol=UDP destination_port=1194 jump=ACCEPT
#    - iptables: chain=INPUT policy=DROP
#    - iptables: chain=FORWARD policy=DROP
#    - iptables: chain=OUTPUT policy=ACCEPT
    # answer the questions for iptables persistent
#    - debconf: name=iptables-persistent question='iptables-persistent/autosave_v4' vtype='boolean' value='true'
#    - debconf: name=iptables-persistent question='iptables-persistent/autosave_v6' vtype='boolean' value='true'
#    - apt: force=yes name=iptables-persistent
